name: neuman_env
channels:
  - pytorch3d
  - bottler
  - iopath
  - fvcore
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=10.2.89
  - fvcore=0.1.5
  - igl=2.2.1
  - iopath=0.1.9
  - nvidiacub=1.10.0
  - python=3.7.10
  - pytorch=1.8.0
  - pytorch3d=0.6.2=py37_cu102_pyt180
  - torchvision=0.9.0
  - pip=21.2.2
  - pip:
    - imageio
    - ipython
    - joblib
    - opencv-python
    - open3d
    - tensorboardx
    - chumpy
    - lpips
    - scikit-image
    - matplotlib